create or replace view DEMO.DEMO.VWTRAFFICIMAGEFORSEARCH(
	FILENAME,
    IMAGE_TEXT,
	DIRECTIONOFTRAVEL,
	ENDING,
	LATITUDE,
	LONGITUDE,
	ROADWAYNAME,
	CAMERA_URL,
	VIDEONAME,
    CREATED_TS
) as 
select R.FILENAME, 
       TO_VARCHAR(R.JSON_DATA) as IMAGE_TEXT, 
       N.DIRECTIONOFTRAVEL, N.ENDING, 
       TO_DECIMAL(N.LATITUDE) as LATITUDE, TO_DECIMAL(N.longitude) as LONGITUDE, 
       N.ROADWAYNAME,
       N.URL2 as CAMERA_URL,  N.VIDEONAME, N.CREATED_TS
from RAWNYCTRAFFICIMAGES R LEFT OUTER JOIN nyctrafficimages N ON R.FILENAME = N.FILENAME
WHERE IMAGE_TEXT is not null 
order by N.CREATED_TS desc;
